source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

workspace 'DIMockServerDemo'

target 'DIMockServerDemo' do
    project 'DIMockServerDemo.xcodeproj'
    pod 'DIMockServer', :path => '../', :configurations => ["Debug"]
    pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git', :branch => 'stable', :configurations => ["Debug"]
    pod 'GRMustache.swift', :configurations => ["Debug"]
    pod 'QorumLogs', :configurations => ["Debug"]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
    target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end